import { Tour } from "@/guides";

export const overview: Tour[] = [
    {
        tour: "overview",
        steps: [
            {
                icon: <>👋</>,
                title: "Welcome to Onborda!",
                content: <>This is step 1 </>,
                selector: "#overview-step1",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 2 </>,
                selector: "#overview-step2",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 3 </>,
                selector: "#overview-step3",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 4 </>,
                selector: "#overview-step4",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 5 </>,
                selector: "#overview-step5",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 6 </>,
                selector: "#overview-step6",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 7 </>,
                selector: "#overview-step7",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 8 </>,
                selector: "#overview-step8",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 9 </>,
                selector: "#overview-step9",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 10 </>,
                selector: "#overview-step10",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 11 </>,
                selector: "#overview-step11",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 12 </>,
                selector: "#overview-step12",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 13 </>,
                selector: "#overview-step13",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 14 </>,
                selector: "#overview-step14",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 15 </>,
                selector: "#overview-step15",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 16 </>,
                selector: "#overview-step16",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 17 </>,
                selector: "#overview-step17",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 18 </>,
                selector: "#overview-step18",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 19 </>,
                selector: "#overview-step19",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 20 </>,
                selector: "#overview-step20",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            }
        ],
    }
];