import { Tour } from "@/guides";

export const profile: Tour[] = [
  {
    tour: "profile",
    steps: [
      {
        icon: <>👋</>,
        title: "Welcome to Onborda!",
        content: <>This is step 1 </>,
        selector: "#profile-step1",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 2 </>,
        selector: "#profile-step2",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 3 </>,
        selector: "#profile-step3",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 4 </>,
        selector: "#profile-step4",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 5 </>,
        selector: "#profile-step5",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 6 </>,
        selector: "#profile-step6",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 7 </>,
        selector: "#profile-step7",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 8 </>,
        selector: "#profile-step8",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 9 </>,
        selector: "#profile-step9",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 10 </>,
        selector: "#profile-step10",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 11 </>,
        selector: "#profile-step11",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 12 </>,
        selector: "#profile-step12",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 13 </>,
        selector: "#profile-step13",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 14 </>,
        selector: "#profile-step14",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 15 </>,
        selector: "#profile-step15",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 16 </>,
        selector: "#profile-step16",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 17 </>,
        selector: "#profile-step17",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 18 </>,
        selector: "#profile-step18",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 19 </>,
        selector: "#profile-step19",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 20 </>,
        selector: "#profile-step20",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      }
    ],
  }
];