import { Tour } from "@/guides";

export const trackerTransaction: Tour[] = [
    {
        tour: "tracker-transaction",
        steps: [
            {
                icon: <>👋</>,
                title: "Welcome to Onborda!",
                content: <>This is step 1 </>,
                selector: "#tracker-transaction-step1",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 2 </>,
                selector: "#tracker-transaction-step2",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 3 </>,
                selector: "#tracker-transaction-step3",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 4 </>,
                selector: "#tracker-transaction-step4",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 5 </>,
                selector: "#tracker-transaction-step5",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 6 </>,
                selector: "#tracker-transaction-step6",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 7 </>,
                selector: "#tracker-transaction-step7",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 8 </>,
                selector: "#tracker-transaction-step8",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 9 </>,
                selector: "#tracker-transaction-step9",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 10 </>,
                selector: "#tracker-transaction-step10",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 11 </>,
                selector: "#tracker-transaction-step11",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 12 </>,
                selector: "#tracker-transaction-step12",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 13 </>,
                selector: "#tracker-transaction-step13",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 14 </>,
                selector: "#tracker-transaction-step14",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 15 </>,
                selector: "#tracker-transaction-step15",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 16 </>,
                selector: "#tracker-transaction-step16",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 17 </>,
                selector: "#tracker-transaction-step17",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 18 </>,
                selector: "#tracker-transaction-step18",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 19 </>,
                selector: "#tracker-transaction-step19",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 20 </>,
                selector: "#tracker-transaction-step20",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            }
        ]
    }
];