import { Tour } from "@/guides";

export const transaction: Tour[] = [
  {
    tour: "transaction",
    steps: [
      {
        icon: <>👋</>,
        title: "Welcome to Onborda!",
        content: <>This is step 1 </>,
        selector: "#transaction-step1",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 2 </>,
        selector: "#transaction-step2",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 3 </>,
        selector: "#transaction-step3",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 4 </>,
        selector: "#transaction-step4",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 5 </>,
        selector: "#transaction-step5",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 6 </>,
        selector: "#transaction-step6",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 7 </>,
        selector: "#transaction-step7",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 8 </>,
        selector: "#transaction-step8",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 9 </>,
        selector: "#transaction-step9",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 5,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 10 </>,
        selector: "#transaction-step10",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 11 </>,
        selector: "#transaction-step11",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 12 </>,
        selector: "#transaction-step12",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 13 </>,
        selector: "#transaction-step13",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 14 </>,
        selector: "#transaction-step14",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 15 </>,
        selector: "#transaction-step15",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 16 </>,
        selector: "#transaction-step16",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 17 </>,
        selector: "#transaction-step17",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 18 </>,
        selector: "#transaction-step18",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 19 </>,
        selector: "#transaction-step19",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 20 </>,
        selector: "#transaction-step20",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      }
    ]
  }
];