export const TRACKER_TRANSACTION_TYPE_MODEL_KEY = 'TRACKER_TRANSACTION_TYPE'
export const TRACKER_TRANSACTION_TYPE_MODEL_RETRY = 2
export const TRACKER_TRANSACTION_MODEL_KEY = 'TRACKER_TRANSACTION'
export const STATISTIC_TRACKER_TRANSACTION_KEY = 'STATISTIC_TRACKER_TRANSACTION'
export const TRACKER_TRANSACTION_MODEL_RETRY = 2
