export const GET_ALL_TRACKER_TRANSACTION_TYPE_KEY = 'TRACKER_TRANSACTION_TYPE/ALL'
export const TRACKER_TRANSACTION_TYPE_MODEL_RETRY = 2
export const GET_ADVANCED_TRACKER_TRANSACTION_KEY = 'TRACKER_TRANSACTION/ADVANCED'
export const STATISTIC_TRACKER_TRANSACTION_KEY = 'STATISTIC_TRACKER_TRANSACTION'
export const TRACKER_TRANSACTION_MODEL_RETRY = 2
