export const TRANSACTION_RETRY = 1
export const PAYMENT_RETRY = 3
export const GET_ADVANCED_TRANSACTION_KEY = 'TRANSACTION/ADVANCED'
export const GET_UNCLASSIFIED_TRANSACTION_KEY = 'TRANSACTION/GET_UNCLASSIFIED'
export const REFETCH_PAYMENT_KEY = 'PAYMENT/REFETCH'
export const GET_ALL_PAYMENT_KEY = 'PAYMENT/ALL'
