interface Step {
    icon: JSX.Element;
    title: string;
    content: JSX.Element; // 
    selector: string; // 
    side: "top" | "right" | "bottom" | "left";
    showControls: boolean;
    pointerPadding?: number;
    pointerRadius?: number;
}

interface Tour {
    tour: string;
    steps: Step[];
}

export const steps: Tour[] = [
    {
        tour: "tracker-transaction",
        steps: [
            {
                icon: <>👋</>,
                title: "Welcome to Onborda!",
                content: <>This is step 1</>,
                selector: "#tracker-step1",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 2</>,
                selector: "#tracker-step2",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 3</>,
                selector: "#tracker-step3",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 4</>,
                selector: "#tracker-step4",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 5</>,
                selector: "#tracker-step5",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 6</>,
                selector: "#tracker-step6",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 7</>,
                selector: "#tracker-step7",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 8</>,
                selector: "#tracker-step8",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 9</>,
                selector: "#tracker-step9",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 10</>,
                selector: "#tracker-step10",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 11</>,
                selector: "#tracker-step11",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            }
        ],
    },
    {
        tour: "dashboard",
        steps: [
            {
                icon: <>👋</>,
                title: "Welcome to Onborda!",
                content: <>This is step 1</>,
                selector: "#tracker-step1",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 2</>,
                selector: "#tracker-step2",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 3</>,
                selector: "#tracker-step3",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 4</>,
                selector: "#tracker-step4",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 5</>,
                selector: "#tracker-step5",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 6</>,
                selector: "#tracker-step6",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 7</>,
                selector: "#tracker-step7",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 8</>,
                selector: "#tracker-step8",
                side: "right",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🪄</>,
                title: "It's like magic!",
                content: <>This is step 9</>,
                selector: "#tracker-step9",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 5,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 10</>,
                selector: "#tracker-step10",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            },
            {
                icon: <>🎉</>,
                title: "Celebrate!",
                content: <>This is step 11</>,
                selector: "#tracker-step11",
                side: "left",
                showControls: true,
                pointerPadding: 0,
                pointerRadius: 11,
            }
        ],
    },
];