export const ACCOUNT_SOURCE_RETRY_QUERY = 2

export const GET_ADVANCED_ACCOUNT_SOURCE_KEY = 'ACCOUNT_SOURCE/ADVANCED'
export const GET_ALL_ACCOUNT_SOURCE_KEY = 'ACCOUNT_SOURCE/ALL'
export const GET_ACCOUNT_SOURCE_BY_ID_KEY = 'ACCOUNT_SOURCE/GET_BY_ID'
