export const initEmptyUser = {
  id: '',
  profession: '',
  fullName: '',
  dateOfBirth: '',
  gender: '',
  username: '',
  email: '',
  isChangeNewPassword: false,
  licenseNumber: '',
  experience: '',
  workplace: '',
  status: '',
  phone_number: '',
  address: '',
  roleId: '',
  forgetPasswordToken: '',
  refresh_token: '',
  emailVerifyToken: '',
  avatarId: '',
  provider: '',
  accessToken: '',
  defaultExpenditureFundId: ''
}
