export const EXPENDITURE_FUND_TYPE_MODEL_RETRY = 2
export const GET_ADVANCED_EXPENDITURE_FUND_KEY = 'EXPENDITURE_FUND/ADVANCED'
export const JOIN_EXPENDITURE_FUND_KEY = 'EXPENDITURE_FUND/JOIN-EXPENDITURE-FUND'
export const GET_STATISTIC_EXPENDITURE_FUND_KEY = 'EXPENDITURE_FUND/STATISTIC/ADVANCED'
export const GET_STATISTIC_DETAIL_OF_FUND_KEY = 'EXPENDITURE_FUND/STATISTIC-DETAIL/ADVANCED'
export const EXPENDITURE_FUND_MODEL_RETRY = 2
