export const EXPENDITURE_FUND_TYPE_MODEL_RETRY = 2
export const GET_ADVANCED_EXPENDITURE_FUND_KEY = 'EXPENDITURE_FUND/ADVANCED'
export const GET_STATISTIC_EXPENDITURE_FUND_KEY = 'EXPENDITURE_FUND/STATISTIC/ADVANCED'
export const EXPENDITURE_FUND_MODEL_RETRY = 2
